apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sb-hello-world
  template:
    metadata:
      labels:
        app: sb-hello-world
    spec:
     containers:
      - name: sb-hello-world
        image: salimburdah/spring-boot-hello-world:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"